### ISSUE TITLE
Доработать базовую генерацию формы в doc

### ISSUE THREAD

**Issue by D-Tretyakov** [D-Tretyakov/schememaster_sou#3]
1. Нужно добавить к модели `Variants` еще одно поле - текст, который должен писаться в сгенерированной форме
2. Написать функцию в `vievs.py,` которая перегоняет заполненную форму в doc

**Comment by Rusakimova** [comment]
Я пока идейно сделала иначе. Я в функции создаю документ, который заполняю шаблонными строками и с ключевыми метками на местах, где возможны варианты. Затем я заполняю эти метки в зависимости от ответа пользователя. На самом деле со стилем пока костыль. Надо получше со шрифтами разобраться.
