### ISSUE TITLE
Генерация .docx

### ISSUE THREAD

**Issue by D-Tretyakov** [D-Tretyakov/schememaster_sou#8]
## Вводная
Сейчас проект немного переделан: старые модельки не используются, появились новые - `Template` и `TextAlias`.

В `Template` содержится весь текст шаблона, у него есть 3 поля: 
- header
- body
- footer
![image](https://user-images.githubusercontent.com/55451601/87918810-9785b100-ca7f-11ea-98dc-7265419b0866.png)
Как должен выглядеть шаблон, можно посмотреть в файлах юристов (как видно, у меня версия шаблона старая, ее надо доработать в админке django).

В `TextAlias` есть 2 поля:
- html_id (это поле содержит id варианта ответа, который указан в html странице шаблона)
  id имеет вид: `c{i}-v{j}` где i - номер вопроса (например, 1 вопрос - это  "1. Истец"), j - номер варианта ответа, для 
  каждого вопроса нумерация ответов начинается с 1.
- text (это поле содержит текст, который нужно подставить в шаблон при выборе конкретно этого варианта ответа)

## Что в итоге требуется
Написать в `schemegen/views.py` вьюху (смотри пример того, как работать с моделями и ответом с формы в функции `get_text`), которая:
1. Правильно форматирует текст (т.е. текст, который должен быть справа, находится справа; жирный текст - жирный (возможно, для этого потребуется добавить какие-то условные обозначения в тексте шаблона) и т.д.)
2. Стоит обратить внимание на прошение и на приложение: там будет динамическая генерация пунктов в зависимости от  выбранных ответов, поэтому нужно придумать способ сделать правильную нумерацию (сейчас там написан костыль, особо не смотри на него)00) )
3. В результате работы должен возвращаться `HttpResponse`, который возвращает файл (смотри, как это должно +- выглядеть [это](https://djangoadventures.com/how-to-create-file-download-links-in-django/) или [это](https://stackoverflow.com/questions/36392510/django-download-a-file#:~:text=6%20Answers&text=You%20can%20add%20%22download%22%20attribute,your%20tag%20to%20download%20files.&text=I've%20found%20Django's%20FileField,a%20section%20on%20managing%20files.))

**Comment by Rusakimova** [comment]
Во время запуска разных комбинаций пока выявились следующие недочеты:
1) в представителях истца отсутствует второй подпункт
2)в требовании о возмещении убытков после второго пункта пропущен \n

**Comment by Rusakimova** [comment]
3. во втором пункте в представителях истца написать "Копия доверенности или иного документа, подтверждающего полномочия представителя (ей)"
